// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXFX0rbcsXbKeKcvEvjPvAXb9ueVdl_Y',
    appId: '1:844328558327:web:bf3704eb02fdce6d417df2',
    messagingSenderId: '844328558327',
    projectId: 'flutter-firebase-571e6',
    authDomain: 'flutter-firebase-571e6.firebaseapp.com',
    storageBucket: 'flutter-firebase-571e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyKltVzJ67DjQMf21TZkH7tG8RZ7zxopo',
    appId: '1:844328558327:android:2feec41c01bf8bf4417df2',
    messagingSenderId: '844328558327',
    projectId: 'flutter-firebase-571e6',
    storageBucket: 'flutter-firebase-571e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRprMTsKGBe5ilEF7T8DgeZ2VyWMelmc8',
    appId: '1:844328558327:ios:e6038a51afa2695e417df2',
    messagingSenderId: '844328558327',
    projectId: 'flutter-firebase-571e6',
    storageBucket: 'flutter-firebase-571e6.appspot.com',
    iosClientId: '844328558327-lvnbkn1736qjavl0kk184r5mnlq8jcr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flfire',
  );
}
